run:
  timeout: 3m

linters:
  disable-all: true
  enable-all: false
  enable:
    - deadcode
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    # we would like to add these
    # - dupl
    # - staticcheck

linters-settings:
  govet:
    # we would like to enable this eventually
    check-shadowing: false
  misspell:
    locale: US

issues:
  max-per-linter: 0
  max-same-issues: 0
